# 装饰器实际使用例子

案例：捕获在使用函数过程中可能出现的错误

```js
const userInfo: any = undefined;
class Demo {
  getName() {
    try {
      return userInfo.name;
    } catch (error) {
      console.log('error');
    }
  }
  getAge() {
    try {
      return userInfo.age;
    } catch (error) {
      console.log('error');
    }
  }
}
```

如果只是一两个函数错误我们一一的进行捕获这不是不可以，但是随着代码量的增加，这样会增加我们的代码量，而且都是一些重复的代码，不方便我们管理，这时我们可以使用函数装饰器

```js
function catchError(target: any, 
                     key: string, 
                     descriptor: PropertyDescriptor) {
  // 获得原来的函数
  const fn = target[key];
  // 统一进行捕获赋值
  descriptor.value = function() {
    try {
      fn();
    } catch (error) {
      console.log(key + '存在问题');
    }
  };
}
class Demo {
  @catchError
  getName() {
    return userInfo.name;
  }
  @catchError
  getAge() {
    return userInfo.age;
  }
}
```

